package license

// Projections — every standards-facing surface generated from the signed
// licence, never authored in parallel.
//
// The rule this file exists to enforce: THE SIGNED LICENCE IS AUTHORITATIVE AND
// EVERYTHING ELSE IS A PROJECTION OF IT. You cannot contradict yourself if
// there is one source. A hand-maintained robots.txt beside a signed license.json
// is two statements that will diverge, and the unsigned one is the one a
// crawler reads.
//
// Where a target vocabulary cannot express a term, it stays unexpressed in that
// surface and the licence link carries it. Never project a condition into a
// bare permission (that over-grants) and never project it into a denial (that
// costs reach — the thing the whole default is designed to protect).

import (
	"encoding/xml"
	"fmt"
	"html"
	"sort"
	"strings"
)

// ContentUsage renders the AIPREF statement of preference as an RFC 8941
// structured-field dictionary — the value of a `Content-Usage` response header
// or of a robots.txt `content-usage` rule.
//
// draft-ietf-aipref-vocab-06 §6: dictionary keys are usage categories, values
// are the tokens y and n. Keys are case-sensitive and a repeated key takes only
// its last value, so emission is ordered and deduplicated by construction.
//
// Returns "" when there is nothing to say. An empty header is worse than no
// header: it parses to a statement that expresses no preference, which is the
// same as silence but looks like an assertion.
func ContentUsage(t *Terms) string {
	if t == nil {
		return ""
	}
	var parts []string
	if t.TrainAI != "" {
		parts = append(parts, "train-ai="+t.TrainAI)
	}
	if t.Search != "" {
		parts = append(parts, "search="+t.Search)
	}
	return strings.Join(parts, ", ")
}

// RobotsRule renders one robots.txt `content-usage` line, optionally scoped to
// a path prefix.
//
// draft-ietf-aipref-attach-04 §3 gives the rule an OPTIONAL path pattern:
//
//	content-usage = *WS "content-usage" *WS ":" *WS
//	                [ path-pattern 1*WS ] usage-pref EOL
//
// That optional path is what makes this epic's hardest requirement reachable. A
// self-hoster on S3 or GitHub Pages cannot set response headers, so if
// per-resource terms only lived in `Content-Usage:` they would be unavailable
// to exactly the people polis exists for. With a path pattern, a post that
// overrides the site default is expressible in a FILE. Headers stay a
// convenience rather than the only home for a term.
func RobotsRule(path string, t *Terms) string {
	pref := ContentUsage(t)
	if pref == "" {
		return ""
	}
	if path == "" {
		return "Content-Usage: " + pref
	}
	return "Content-Usage: " + path + " " + pref
}

// RobotsOptions carries everything robots.txt needs beyond the terms
// themselves.
type RobotsOptions struct {
	// SiteTerms is the site default, from license.json. Nil means the site has
	// stated no terms — in which case NOTHING is emitted rather than a
	// permissive default being invented on the author's behalf.
	SiteTerms *Terms
	// Overrides maps a URL path prefix to the terms materialised for the works
	// under it, for works whose terms differ from the site default.
	Overrides map[string]*Terms
	// RSLURL is the absolute URL of rsl.xml, referenced by RSL's `License:`
	// directive. Empty omits the directive.
	RSLURL string
	// SitemapURL is preserved if the caller wants it emitted alongside.
	SitemapURL string
}

// RobotsHeader opens every robots.txt polis generates, and it is the block's
// SELF-IDENTIFYING BOUNDARY as much as it is a comment. A consumer with no copy
// of the site — `polis validate <url>` reading the public wire, where an edge
// may have prepended directives of its own — finds the site's own section by
// looking for exactly these bytes.
//
// ⛔ It is a const rather than six WriteString calls so the generator and the
// finder cannot drift. A checker carrying its own copy of this string would
// report "polis's section is missing" on the day someone fixed a typo here.
const RobotsHeader = "# Generated by polis from this site's signed licence.\n" +
	"# The signed source of truth is linked from /.well-known/polis (\"license\").\n" +
	"# Edits here do not change the terms — they are overwritten on the next render.\n" +
	"#\n" +
	"# Content-Usage: IETF AIPREF (draft-ietf-aipref-attach-04 §3) — a PREFERENCE signal.\n" +
	"# License:      RSL — the licence terms, including attribution.\n" +
	"\n"

// Robots renders a complete robots.txt.
//
// Two standards attach here and they do different jobs, which is the whole
// composition rule in one file: the `content-usage` rule carries the AIPREF
// PREFERENCE signal, and the `License:` directive points at RSL, which carries
// the actual LICENCE TERMS — attribution, extent, compensation — that AIPREF's
// y/n vocabulary has no way to express.
//
// Returns "" when there is nothing to say, so a site that has stated no terms
// gets no robots.txt rather than one asserting silence.
func Robots(opts RobotsOptions) string {
	rules := []string{}
	if r := RobotsRule("", opts.SiteTerms); r != "" {
		rules = append(rules, r)
	}

	// Deterministic ordering: rule order carries no semantics per attach-04
	// §3.1 ("The ordering of rules in a group carries no semantics"), but
	// byte-stable output keeps regeneration from churning the file.
	paths := make([]string, 0, len(opts.Overrides))
	for p := range opts.Overrides {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		if r := RobotsRule(p, opts.Overrides[p]); r != "" {
			rules = append(rules, r)
		}
	}

	if len(rules) == 0 && opts.RSLURL == "" {
		return ""
	}

	var b strings.Builder
	b.WriteString(RobotsHeader)
	b.WriteString("User-Agent: *\n")
	b.WriteString("Allow: /\n")
	for _, r := range rules {
		b.WriteString(r + "\n")
	}
	if opts.RSLURL != "" {
		b.WriteString("License: " + opts.RSLURL + "\n")
	}
	if opts.SitemapURL != "" {
		b.WriteString("\nSitemap: " + opts.SitemapURL + "\n")
	}
	return b.String()
}

// ---------- RSL ----------

// RSL is where the terms AIPREF structurally cannot express live.
//
// Two of them matter here:
//
//  1. ATTRIBUTION. A free licence with mandatory attribution is a grant on a
//     condition, and AIPREF's vocabulary is y/n with no conditions at all. RSL
//     carries it as <payment type="attribution">.
//
//  2. INFERENCE-TIME USE — the work fetched and summarised into an answer NOW.
//     This is the axis that is actually hurting publishers today, and AIPREF
//     cannot say it: `search` EXCLUDES summarisation by definition (vocab-06
//     §4.2, "This category does not include the use of assets to generate
//     summaries"), and `train-ai` is about model production, not use. So an
//     answer engine that summarises without linking back falls under NEITHER
//     category and resolves to `unknown` — silence, which is latitude to act
//     and claim ambiguity. RSL names it: `ai-input`.
//
// This is the composition rule working as designed: the preference rides
// AIPREF, the condition rides RSL, and neither surface over-grants relative to
// the other.

// rslDoc models the subset of RSL 1.0 we emit (namespace
// https://rslstandard.org/rsl).
type rslDoc struct {
	XMLName xml.Name    `xml:"rsl"`
	NS      string      `xml:"xmlns,attr"`
	Content *rslContent `xml:"content"`
}

type rslContent struct {
	URL     string    `xml:"url,attr"`
	License *rslTerms `xml:"license"`
}

type rslTerms struct {
	Permits   []rslRule   `xml:"permits,omitempty"`
	Prohibits []rslRule   `xml:"prohibits,omitempty"`
	Payment   *rslPayment `xml:"payment,omitempty"`
	Terms     string      `xml:"terms,omitempty"`
}

// rslRule is a <permits> or <prohibits>: a type attribute plus a vocabulary
// value. type="usage" values are RSL's own: all, ai-all, ai-train, ai-input,
// ai-index, search.
type rslRule struct {
	Type  string `xml:"type,attr"`
	Value string `xml:",chardata"`
}

type rslPayment struct {
	Type string `xml:"type,attr"`
}

// RSL renders rsl.xml for a set of terms.
//
// Nothing is asserted that the terms do not state — an absent AIPREF value
// produces no RSL rule, because absent means unstated and inventing a rule
// would be putting words in the author's mouth in the one surface a lawyer
// would read.
//
// Returns "" when there are no terms to project.
func RSL(t *Terms, contentURL string) (string, error) {
	if t == nil {
		return "", nil
	}

	terms := &rslTerms{Terms: t.Terms}

	// AIPREF categories map onto RSL usage values of the same meaning.
	for _, m := range []struct{ val, usage string }{
		{t.TrainAI, "ai-train"},
		{t.Search, "search"},
	} {
		switch m.val {
		case Allow:
			terms.Permits = append(terms.Permits, rslRule{Type: "usage", Value: m.usage})
		case Disallow:
			terms.Prohibits = append(terms.Prohibits, rslRule{Type: "usage", Value: m.usage})
		}
	}

	// ai-input is RSL-only — see the note at the top of this section.
	switch t.AIInput {
	case Allow:
		terms.Permits = append(terms.Permits, rslRule{Type: "usage", Value: "ai-input"})
	case Disallow:
		terms.Prohibits = append(terms.Prohibits, rslRule{Type: "usage", Value: "ai-input"})
	}

	if t.Attribution == AttributionRequired {
		// RSL expresses "free, but you must credit me" as a payment of type
		// attribution — the price of the grant is the credit.
		terms.Payment = &rslPayment{Type: "attribution"}
	}

	doc := rslDoc{
		NS: "https://rslstandard.org/rsl",
		Content: &rslContent{
			URL:     contentURL,
			License: terms,
		},
	}

	body, err := xml.MarshalIndent(doc, "", "  ")
	if err != nil {
		return "", fmt.Errorf("marshal RSL: %w", err)
	}
	return xml.Header + string(body) + "\n", nil
}

// ---------- HTML head ----------

// HeadHTML renders the discovery elements for a rendered page's <head>: a
// `<link rel="license">` and the AIPREF preference as a `<meta>`.
//
// This is where the real work of the licence lives, because crawlers read the
// published site and not the markdown. A signature nobody can see from a fetch
// is a signed note in a drawer.
//
// Returns "" for nil terms.
func HeadHTML(t *Terms) string {
	if t == nil {
		return ""
	}
	var b strings.Builder
	if t.Terms != "" {
		fmt.Fprintf(&b, `<link rel="license" href="%s">`+"\n    ", html.EscapeString(t.Terms))
	}
	if cu := ContentUsage(t); cu != "" {
		fmt.Fprintf(&b, `<meta name="content-usage" content="%s">`+"\n    ", html.EscapeString(cu))
	}
	if t.Profile != "" {
		fmt.Fprintf(&b, `<meta name="polis-license-profile" content="%s">`+"\n    ", html.EscapeString(t.Profile))
	}
	return strings.TrimRight(b.String(), "\n ")
}

// LinkHeader renders the value of an HTTP `Link:` header with rel="license".
// Cheap, and read by things that never parse HTML.
func LinkHeader(t *Terms) string {
	if t == nil || t.Terms == "" {
		return ""
	}
	return "<" + t.Terms + ">; rel=\"license\""
}
