package agent

import (
	"encoding/json"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"strings"

	"github.com/vdibart/polis-cli/cli-go/pkg/atomicfile"
	"github.com/vdibart/polis-cli/cli-go/pkg/attestation"
	"github.com/vdibart/polis-cli/cli-go/pkg/bundle"
	"github.com/vdibart/polis-cli/cli-go/pkg/site"
)

// What an agent is to this site — the PROJECTION (epic 11 D8, epic 46 R12).
//
// ⛔ A PROJECTION OF THE GRANT RECORDS, NEVER A SOURCE. agents.json and the page
// are regenerated from the records on every grant or withdrawal write, may be
// regenerated by anyone at any time, and are NEVER CITED IN A SIGNATURE — the
// marker cites the grant record's own URL (Law 1's corollary).
//
// ⭐ DISCOVERY IS BY POINTER: `.well-known/polis` → `agents`. The files live under
// the attestation type's MOUNT, resolved from the site's bundle, so the path
// is user-configurable like the licence's and cannot collide with a user page
// at the site root.
//
// A site that never had a grant publishes nothing: no pointer, no file.
// Absence is never a finding.

const (
	// AgentsFilename is the machine-readable projection.
	AgentsFilename = "agents.json"
	// AgentsPageDir holds the human page, index.html.
	AgentsPageDir = "agents"
	// ProjectionType names the projection's format.
	ProjectionType = "pub.polis.agents"
)

// MountDir returns the site-relative directory the projection is written under
// — the attestation type's mount, honouring the site's bundle.
func MountDir(siteDir string) string {
	b, err := bundle.LoadBundle(filepath.Join(siteDir, "content", "pub.polis.core", "bundle.json"))
	if err == nil {
		if dir, err := b.MountDir(attestation.TypeName); err == nil {
			return dir
		}
	}
	return "attestations"
}

// PointerValue is the site-relative URL the `agents` pointer carries.
func PointerValue(siteDir string) string {
	return "/" + filepath.ToSlash(filepath.Join(MountDir(siteDir), AgentsFilename))
}

// Projection is the agents.json document.
type Projection struct {
	Type string `json:"type"`
	// Note says what this file is, for anyone who opens it.
	Note   string           `json:"note"`
	Agents []ProjectionItem `json:"agents"`
}

// ProjectionItem is one grant record.
type ProjectionItem struct {
	Agent       string `json:"agent"`
	Provider    string `json:"provider"`
	Behaviours  string `json:"behaviours"`
	Basis       string `json:"basis"`
	Grant       string `json:"grant"`
	Asserted    string `json:"asserted"`
	State       string `json:"state"`
	WithdrawnAt string `json:"withdrawn_at,omitempty"`
	Withdrawal  string `json:"withdrawal,omitempty"`
}

const projectionNote = "Generated from this site's grant records. Cite a grant's own URL, never this file."

// RefreshProjections rewrites agents.json, the page and the pointer from the
// site's grant records — or removes all three when there are none.
//
// ⚠️ The pointer is written only when it CHANGES. `.well-known/polis` is tracked
// by Patrol (mtime) and Judge (hash), so rewriting an identical value on every
// grant would turn each refresh into a finding.
func RefreshProjections(siteDir string) error {
	grants, err := attestation.Grants(siteDir, "")
	if err != nil {
		return fmt.Errorf("read grants: %w", err)
	}
	mount := filepath.Join(siteDir, MountDir(siteDir))
	jsonPath := filepath.Join(mount, AgentsFilename)
	pagePath := filepath.Join(mount, AgentsPageDir, "index.html")

	if len(grants) == 0 {
		_ = os.Remove(jsonPath)
		_ = os.Remove(pagePath)
		_ = os.Remove(filepath.Dir(pagePath))
		if site.AgentsPointer(siteDir) != "" {
			return site.SetAgentsPointer(siteDir, "")
		}
		return nil
	}

	p := Projection{Type: ProjectionType, Note: projectionNote, Agents: []ProjectionItem{}}
	for _, g := range grants {
		it := ProjectionItem{
			Agent: g.Agent, Provider: g.Record.Payload[attestation.GrantKeyProvider],
			Behaviours: g.Record.Payload[attestation.GrantKeyBehaviours], Basis: g.Basis,
			Grant: g.URL, Asserted: g.Record.Asserted, State: "live",
		}
		switch {
		case g.Withdrawn:
			it.State, it.WithdrawnAt, it.Withdrawal = "withdrawn", g.WithdrawnAt, g.WithdrawalURL
		case g.Signature != attestation.StatusValid:
			it.State = "unverified"
		}
		p.Agents = append(p.Agents, it)
	}
	data, err := json.MarshalIndent(p, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(pagePath), 0755); err != nil {
		return fmt.Errorf("create projection dir: %w", err)
	}
	if err := atomicfile.WriteFile(jsonPath, append(data, '\n'), 0644); err != nil {
		return fmt.Errorf("write %s: %w", AgentsFilename, err)
	}
	if err := atomicfile.WriteFile(pagePath, renderPage(p), 0644); err != nil {
		return fmt.Errorf("write agents page: %w", err)
	}
	if want := PointerValue(siteDir); site.AgentsPointer(siteDir) != want {
		return site.SetAgentsPointer(siteDir, want)
	}
	return nil
}

func renderPage(p Projection) []byte {
	var b strings.Builder
	b.WriteString("<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">\n")
	b.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	b.WriteString("<title>Helpers on this site</title></head>\n<body>\n<main>\n<h1>Helpers on this site</h1>\n")
	b.WriteString("<p>Software that works for the owner of this site, and what each one was switched on for. ")
	b.WriteString("Every act a helper makes is marked with its name and a link to the record below it acted under.</p>\n")
	for _, it := range p.Agents {
		name := it.Agent
		if it.Agent == Rosie {
			name = "Rosie"
		}
		fmt.Fprintf(&b, "<section>\n<h2>%s <small>(%s)</small></h2>\n<ul>\n", html.EscapeString(name), html.EscapeString(it.State))
		fmt.Fprintf(&b, "<li>Provided by %s</li>\n", html.EscapeString(it.Provider))
		fmt.Fprintf(&b, "<li>What she may do: %s</li>\n", html.EscapeString(describeBehaviours(it.Behaviours)))
		fmt.Fprintf(&b, "<li>%s on %s</li>\n", html.EscapeString(describeBasis(it.Basis)), html.EscapeString(it.Asserted))
		if it.State == "withdrawn" {
			fmt.Fprintf(&b, "<li>Switched off on %s</li>\n", html.EscapeString(it.WithdrawnAt))
		}
		fmt.Fprintf(&b, "<li>Record: <a href=\"%s\">%s</a></li>\n</ul>\n</section>\n",
			html.EscapeString(it.Grant), html.EscapeString(it.Grant))
	}
	b.WriteString("</main>\n</body></html>\n")
	return []byte(b.String())
}

func describeBehaviours(set string) string {
	if s, v, ok := attestation.ParseBehaviours(set); ok && s == RosieSet && v >= 1 {
		return "approve or turn away comments, using the owner's own rules (" + set + ")"
	}
	return set
}

func describeBasis(basis string) string {
	switch basis {
	case attestation.CustodyBasisHostingTerms:
		return "Switched on by the hosting service"
	case attestation.CustodyBasisUserSigned:
		return "Switched on by the owner"
	}
	return "Switched on"
}
